### ISSUE TITLE
Release procedure

### ISSUE THREAD

**Issue by cxong** [dorkster/freeblocks#10]
I've noticed you made some nice changes recently, which should be released soon. Let's work out a release procedure and some details.

- Frequency - how often do you want to do releases?
- Binary hosting? Sourceforge is mature and has analytics, but github also allows attaching binaries to releases, which is simpler. For the GCW-Zero release, it's more convenient for the official repo to maintain a single link to the latest release.

**Comment by dorkster** [comment]
I have not set schedule for doing releases. Versions will come as they happen.

I'm fine with using Github for hosting binary releases. For now, I've tagged the latest set of changes as a release: https://github.com/dorkster/freeblocks/releases/tag/v0.3
