### ISSUE TITLE
GCW-Zero enhancements

### ISSUE THREAD

**Issue by cxong** [dorkster/freeblocks#14]
- Exit out of all menus, quit game from main menu, using select (SDLK_ESCAPE)
- Pause in game using start (SDLK_RETURN)
- Update game icon

SDL key mappings here: http://wiki.surkow.com/Tutorials:SDL#Buttons

**Comment by dorkster** [comment]
This has been completed.

Key binds: https://github.com/dorkster/freeblocks/commit/d58eb1c1d669588c03b071a95fa612897fbaacbf
New icon: https://github.com/dorkster/freeblocks/commit/5a4808cd3e570b0fb62d33140cb25f80d9cdee66

I've also updated the README to include a section for [GCW-Zero controls](https://github.com/dorkster/freeblocks#controls-gcw-zero).
