### ISSUE TITLE
Change block set to use shapes

### ISSUE THREAD

**Issue by cxong** [dorkster/freeblocks#5]
The current block set uses colours only to differentiate. If the blocks incorporated different shapes, this will make it easier to tell apart, as well as improving accessibility.

The original Tetris Attack used inset shapes:
![image](https://cloud.githubusercontent.com/assets/1083215/5994369/9c2631f2-aac4-11e4-9ee9-e8dcb18c7fc7.png)

Other match-3 games use different shaped blocks (different jewels, candies, animals).

Unfortunately Kenney's blocks don't have enough shapes for all 6 colours, so a new block set is required.

**Comment by dorkster** [comment]
Good idea. I'll work on adding shape overlays to the existing assets.
